# Having two seperate playbooks can be optimized, but it does the job for now
- hosts: flash01
  remote_user: root
  become: yes
  vars_files:
    - vars/docker.yml
  roles:
    - geerlingguy.docker
  tasks:
    - name: Start Flash container
      shell: docker run --name flash --restart always -d -p 25565:25565 freggyy/lbwl-flash:1.0.0