- hosts: hub
  remote_user: root
  become: yes
  vars_files:
    - vars/docker.yml
  roles:
    - geerlingguy.docker
  tasks:
    - name: Start BungeeCord container
      shell: docker run --name bungee --restart always -d -p 25565:25577 -v /etc/config.yml:/config/config.yml itzg/bungeecord
    - name: Start lobby container
      shell: docker run --name lobby --restart always -d -p 25566:25565 freggyy/lbwl-lobby:1.0.0

