apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: monitoring-ingress
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: loki-grafana
          servicePort: 80