all:
  vars:
    ansible_user: root
    docker_dns_servers_strict: false
  hosts:
    etcd01.mars.luxor.cloud:
      ansible_host: 94.130.182.241

    master01.mars.luxor.cloud:
      ansible_host: 94.130.176.206
    
    worker01.mars.luxor.cloud:
      ansible_host: 94.130.177.79
    
    worker02.mars.luxor.cloud:
      ansible_host: 94.130.181.208

  children:
    k8s-cluster:
      children:
        etcd:
          hosts:
            etcd01.mars.luxor.cloud:
        kube-master:
          hosts:
            master01.mars.luxor.cloud:
        kube-node:
          hosts:
            worker01.mars.luxor.cloud:
            worker02.mars.luxor.cloud:
